# Generated by Django 3.0.2 on 2020-01-10 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200109_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='patient_number',
            field=models.IntegerField(null=True),
        ),
    ]
