# Generated by Django 3.0.2 on 2020-01-10 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_userprofile_patient_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.TextField()),
                ('patient_number', models.IntegerField(null=True)),
                ('input_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
