# Generated by Django 3.0.2 on 2020-01-10 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_patientdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdata',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_patient_data', to='api.UserProfile'),
        ),
    ]
