# Generated by Django 3.0.2 on 2020-01-10 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200110_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdata',
            name='patient_name',
            field=models.TextField(),
        ),
    ]
