# Generated by Django 3.0.2 on 2020-01-10 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200110_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdata',
            name='patient_name',
            field=models.TextField(editable=False),
        ),
    ]
