# Generated by Django 3.0.2 on 2020-01-10 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200110_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdata',
            name='assigned_doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ass_doc_patient_data', to='api.UserProfile'),
        ),
        migrations.AddField(
            model_name='patientdata',
            name='image',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='patientdata',
            name='input_place',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='patientdata',
            name='medical_personnel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='med_per_patient_data', to='api.UserProfile'),
        ),
        migrations.AddField(
            model_name='patientdata',
            name='result',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='patientdata',
            name='status',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_patient_data', to='api.UserProfile'),
        ),
    ]
